removed resource properties from score files
score-spec/score-helm pull request #20
Opened 2023-06-05 19:38 UTC by sujaya-sys

#### Description
We are planning to deprecate resource properties in the Score spec: https://github.com/score-spec/spec/issues/61

#### What does this PR do?
It removes resource properties from the example score.yaml files we store in this repo

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New chore (expected functionality to be implemented)

#### Checklist:

- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] I've signed off with an email address that matches the commit author.

2023-06-06 10:17 UTC, ghen requested changes
CLI code needs to be updated. Otherwise these examples won't work and that would confuse the users.

Please wait for code changes before approving/merging these changes.

2023-06-15 14:17 UTC, ghen reviewed
LGTM.
Would appreciate someone else to review these changes as well.

2023-07-04 07:40 UTC, chrishumanitec requested changes
One typeo otherwise looks good.

2023-07-04 07:40 UTC, chrishumanitec commented on internal/helm/convert_test.go
> +						Type: "posgres",
should be `postgres` missing a `t`

2023-07-04 08:07 UTC, ghen commented on internal/helm/convert_test.go
> +						Type: "posgres",
Fixed.

2023-07-05 07:59 UTC, ghen approved these changes

2023-07-05 07:59 UTC, merged